<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <title>Page not found at <?php echo $this->requestURL; ?></title>
  <meta name="robots" content="NONE,NOARCHIVE">
  <style type="text/css">
    html * { padding:0; margin:0; }
    body * { padding:10px 20px; }
    body * * { padding:0; }
    body { font-family: Aquabase, "Arial", "sans-serif"; background: #eee; font-size: 13px; }
    body>div { border-bottom:1px solid #ddd; }
    h1 { font-weight:normal; margin-bottom:.4em; }
    h1 span { font-size:60%; color:#666; font-weight:normal; }
    table { border:none; border-collapse: collapse; width:100%; }
    td, th { vertical-align:top; padding:2px 3px; }
    th { width:12em; text-align:right; color:#666; padding-right:.5em; }
    #info { background:#fff; }
    #info ol { margin: 0.5em 4em; }
    #info ol li { font-family: monospace; }
	ol li { font-family: Consolas, "Arial", sans-serif; font-size: 11px; }
	ol li:hover { background: #FFE3E4; font-weight: bold; }
    #summary { background: #e2f5ff; }
    #explanation { background:#eee; border-bottom: 0px none; }
  </style>
</head>
<body>
  <div id="summary">

    <h1>Page not found <span>(404)</span></h1>
    <table class="meta">
      <tr>
        <th>Request Method:</th>
        <td><?php echo $this->method; ?></td>
      </tr>
      <tr>

        <th>Request URL:</th>
      <td><?php echo $this->requestURL; ?></td>
      </tr>
    </table>
  </div>
  <div id="info">

      <p>
      Using the system routes given,
      Unus tried these URL patterns, in this order:
      </p>

      <ol>
        <?php
			foreach ($this->urls as $k => $v) {
				echo '<li>'.htmlentities(str_replace(Unus::getPath(), '', $v['pattern'])).'</li>';
			}
		?>
      </ol>
      <p>The current URL, <code><?php echo $this->requestURL; ?></code>, didn't match any of these.</p>

  </div>
  <div id="explanation">
    <p>
      You are recieving this message because you have <code>Unus::isDeveloperMode();</code> set to <code>on</code>.
	  Setting <code>Unus::isDeveloperMode('off');</code> will trigger a 404 Error and a catchable event of <code>http_code_404</code>
	</p>
	<br />
	<p>
	  You can capture this event by using <code>Unus::addObserver('404 Event Handler', array('class', 'method'), 'http_code_404');</code>
	</p>
	<br />
	<p>
	  For more information on how to handle 404 Errors you may visit <a href="http://docs.unusframework.com/404" target="_blank">Unus 404 Error Handling</a>
	</p>
	<br />
  </div>
</body>
</html>
