<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <title>500 Internal Server Error <?php echo $this->requestURL; ?></title>
  <meta name="robots" content="NONE,NOARCHIVE">
  <style type="text/css">
    html * { padding:0; margin:0; }
    body * { padding:10px 20px; }
    body * * { padding:0; }
    body { font-family: Aquabase, "Arial", "sans-serif"; background: #eee; font-size: 13px; }
    body>div { border-bottom:1px solid #ddd; }
    h1 { font-weight:normal; margin-bottom:.4em; }
    h1 span { font-size:60%; color:#666; font-weight:normal; }
    table { border:none; border-collapse: collapse; width:100%; }
    td, th { vertical-align:top; padding:2px 3px; }
    th { width:12em; text-align:right; color:#666; padding-right:.5em; }
    #info { background:#fff; }
    #info ol { margin: 0.5em 4em; }
    ol li { font-family: Consolas, "Arial", sans-serif; font-size: 11px; }
	/*ol li ol li:hover { background: #FFE3E4; font-weight: bold; }*/
    #summary { background: #e3ffe3; }
    #explanation { background:#eee; border-bottom: 0px none; }
	.explanation { margin: 10px 0px 10px; background: #F2F2F2; border: 1px solid #EFEFEF; font-family: Consolas, "Arial", sans-serif; font-size: 10px; }
	/*li.one { background: #F2F2F2; }*/
	/*li.two { background: #fff; }*/
  </style>
  <script type="text/javascript" src="<?=$this->media_url?>js/jquery/lib/jquery.min.js"></script>
</head>
<body>
  <div id="summary">

    <h1>Internal Server Error <span>(500)</span></h1>
    <table class="meta">
      <tr>
        <th>Request Method:</th>
        <td><?php echo $this->method; ?></td>
      </tr>
      <tr>
        <th>Request URL:</th>
      <td><?php echo $this->requestURL; ?></td>
      </tr>
	  <tr>
        <th>PHP Version:</th>
      <td><?=phpversion();?></td>
      </tr>
	  <tr>
        <th>Server Time:</th>
      <td><?=date('l F jS, Y g:i:sa O');?></td>
      </tr>
	  <tr>
        <th>Exception Message:</th>
      <td><?php echo $this->exception->getMessage(); ?></td>
      </tr>
	  <tr>
        <th>Exception File:</th>
      <td><?php echo $this->file; ?></td>
      </tr>
	  <tr>
        <th>Exception Line:</th>
      <td><?php echo $this->line; ?></td>
      </tr>
	  <tr>
        <th>Code Block:</th>
      <td><pre style="padding-left: 32px;"><?php echo $this->lineError; ?></pre></td>
      </tr>
    </table>
  </div>
  <div id="info">
	  <?php
	  $javascript = null;
		$trace = array();
		$i = 0;
			foreach ($this->trace as $k => $v) {
			  $error = null;
			  $error = '<span class="explanation" style="float: right; font-weight: bold; display: block; border: 1px dashed #000; margin: 2px 0 2px; padding: 2px 5px;" id="'.$i.'-show">+</span>';
			  $file = (isset($v['file'])) ? $v['file'] : $this->file;
			  $line = (isset($v['line'])) ? $v['line'] : $this->line;
			  $class = (isset($v['class'])) ? $v['class'] : '';
			  $type = (isset($v['type'])) ? $v['type'] : '';
			  $function = (isset($v['function'])) ? $v['function'] : 'Unknown Function or Method';
			  $args = (isset($v['args'])) ? $v['args'] : '';
			  @$error .= ''.$file.'('.$line.'): '.$class.$type.$function.'('.Unus_Exception::parseArgs($args).')';
			  $file = Unus_Helper_File_Read_Lines::parse($file, $line, 10);
			  $lineError = '<ol>';
			  foreach ($file as $k => $v) {
				 $use = ($k % 2) ? 'one' : 'two';
				  $lineError .= '<li value="'.$k.'" class="'.$use.'">';
				  if ($k == $line) {
					  $lineError .= '<strong>';
				  }

				  $lineError .= htmlentities($v);
				  if ($k == $line) {
					  $lineError .= '</strong>';
				  }
				  $lineError .= '</li>';
			  }
			  $lineError .= '</ol>';
			  $error .= '<pre id="'.$i.'-pre" style="display: none" class="explanation">'.$lineError.'</pre><div style="clear: both;"></div>';
			  $trace[] = $error;
			  $javascript .= '$("#'.$i.'-show").click(function(){
				if ($("#'.$i.'-pre").css("display") == "none") {
				  $("#'.$i.'-pre").show("fast");
				  $("#'.$i.'-show").html("-");
				} else {
				  $("#'.$i.'-pre").hide("fast");
				  $("#'.$i.'-show").html("+");
				}
			  });';
			  $i++;
			}
		?>
	  <script type="text/javascript">
		$(document).ready(function(){
		  <?=$javascript?>
		});
	  </script>
	  <p>
		Backtrace (<strong><?=count($trace)?></strong>) Results Found
      </p>
      <ol>
		<?php
		$i = 0;
		foreach ($trace as $k => $v) {
		  echo '<li id="'.$i.'">'.$v.'</li>';
		  $i++;
		}
		?>
      </ol>
	<!--  <p id="debug-click">-->
	<!--	Debug Information-->
	<!--	<script type="text/javascript">-->
	<!--	$(document).ready(function(){-->
	<!--	  $("#debug-click").click(function(){-->
	<!--			if ($("#debug").css("display") == "none") {-->
	<!--			  $("#debug").show("fast");-->
	<!--			} else {-->
	<!--			  $("#debug").hide("fast");-->
	<!--			}-->
	<!--		  });-->
	<!--	});-->
	<!--	</script>-->
	<!--	<pre id="debug" style="display: none;" class="explanation">-->
	<!--	</pre>-->
	<!--  </p>-->
      <p>
		You may also check the contents of the error log file for more information, or enable FirePHP <code>Unus_Development::setFirePHP(true);</code> to send
		exceptions to Firebug
	  </p>
  </div>
  <div id="explanation">
    <p>
      You are recieving this message because you have <code>Unus::isDeveloperMode();</code> set to <code>on</code>.
	  Setting <code>Unus::isDeveloperMode('off');</code> will trigger a 500 Error and a catchable event of <code>http_code_500</code>
	</p>
	<br />
	<p>
	  You can capture this event by using <code>Unus::addObserver('500 Event Handler', array('class', 'method'), 'http_code_500');</code>
	</p>
	<br />
	<p>
	  For more information on how to handle 500 Errors you may visit <a href="http://docs.unusframework.com/500" target="_blank">Unus 500 Error Handling</a>
	</p>
	<br />
	<p>
	  Think this could be a possiable bug <a href="http://bugs.unusframework.com/report/">click here</a> to report it automatically
	</p>
	<br />
  </div>
</body>
</html>
