<?=$this->getHtml('body/head')?>
	<script>
	$(document).ready(function(){
		$("#back_login").click(function(){
			window.location = "<?php echo Unus::getAdminPath(); ?>login";
		})
	})
    </script>
	<div id="login">
		<div id="content">
			<div id="logo">
				<h1>
					Lost Password
				</h1>
				<span>
					Lost Password
				</span>
			</div>
			<div id="box">
				<div class="__UN_ALERT">
					To reset your password, enter your username and email address associated with your account below
				</div>
				<?php
				if ($this->session->getErrorMessage()) {
					echo '<div class="__UN_error">'.$this->session->getErrorMessage(true).'</div>';
				}
				if ($this->session->getMessage()) {
					echo '<div class="__UN_MSG">'.$this->session->getMessage(true).'</div>';
				}
				?>
				<?php
				if ($this->lock_out) {
					echo '<div class="__UN_error">
					You have reached the maximum attempts allowed to login <br /><br />
					You will be unable to attempt another login until <strong>'.date('m/d/y h:ia', $this->session->getSessionExpire('admin_login_lockout')).'</strong>
					</div>';
				} else {
					echo $this->form->render();
				}
				?>
				<div class="clear"></div>
			</div>
		</div>
	</div>
<?=$this->getHtml('body/foot')?>
