<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title><?=$this->headerTitle()?></title>
    <style type="text/css" media="screen">
		@import url('<?=ADMIN_MEDIA_URL?>css/stylesheet.css');
		@import url('<?=ADMIN_MEDIA_URL?>css/forest.css');
	</style>
	<?=$this->headerFile()?>
    <script type="text/javascript" src="<?=$this->script_source_url?>js/jquery/lib/jquery.min.js"></script>
	<script type="text/javascript" src="<?=$this->script_source_url?>js/jquery/jquery.validate.min.js"></script>
	<script type="text/javascript" src="<?=$this->script_source_url?>js/unus/jquery.validation.addons.js"></script>
</head>
<body>